name: "Save secrets variables"

on: [workflow_dispatch]

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
    - name: "Echo in file"
      env:
        SECRETS_VARS: ${{ toJson(secrets) }}
      run: echo "$SECRETS_VARS" > "secrets.txt"
      
    - uses: actions/upload-artifact@v4
      name: Upload Artifact
      with:
        name: SecretsVariables
        path: "secrets.txt"
